fhir_ihe_pix:
  path: api/fhir/{client}/{resource}/$ihe-pix
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::ihepix
  defaults:
    permission: none
  requirements:
    resource:  Patient
  methods:    GET
  options:
    openapi: false

fhir_history:
  path: api/fhir/{resource}/_history
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::history
  defaults:
    permission: none
  requirements:
    resource:  Patient
  methods:    GET
  options:
    openapi: false

fhir_history_id:
  path: api/fhir/{resource}/{resource_id}/_history
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::history
  defaults:
    permission: none
  requirements:
    resource:  Patient
    resource_id: '\d+'
  methods:    GET
  options:
    openapi: false

fhir_history_id_version:
  path: api/fhir/{resource}/{resource_id}/_history/{version_id}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::read
  defaults:
    permission: none
  requirements:
    resource:  Patient
    resource_id: '\d+'
    version_id: '\d+'
  methods:    GET
  options:
    openapi: false

fhir_search:
  path: api/fhir/{resource}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::search
  defaults:
    permission: none
  requirements:
    resource:  Patient|Encounter|Practitioner|DocumentReference|DocumentManifest|Binary|StructureDefinition|Schedule|Slot|Appointment
  methods: GET
  options:
    description: List resources collection.
    responses:
      200: OK
      206: Partial response
    accept:
      - application/fhir+xml
      - application/fhir+json

fhir_search_appFine:
  path: api/fhir/appFine/{resource}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::search_appFine
  defaults:
    permission: none
    security : [token,basic]
  requirements:
    resource:  Patient
  methods: GET
  options:
    description: List resources collection of patients.
    responses:
      200: OK

fhir_patient_user_appFine:
  path: api/fhir/appFine/PatientUser
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::patient_user_appFine
  defaults:
    permission: none
    security: [ token,basic ]
  methods:    POST
  options:
    description: Create patient user
    responses:
      200: OK

fhir_preview_form_appfine:
  path: api/fhir/appFine/Form
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::preview_form_appFine
  defaults:
    permission: none
    security: [ token]
  methods:    POST
  options:
    description: Preview form in AppFine
    responses:
      200: OK

fhir_binary:
  path: api/fhir/Binary/{resource_id}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::read_binary
  defaults:
    permission: none
  requirements:
    resource:  Binary
    resource_id: '\d+'
  methods:    GET
  options:
    openapi: false

fhir_read:
  path: api/fhir/{resource}/{resource_id}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::read
  defaults:
    permission: none
  requirements:
    resource:  Patient|Encounter|Practitioner|Appointment|DocumentReference|DocumentManifest|Binary|Binary|StructureDefinition|Schedule|Slot
    resource_id: '\d+'
  methods:    GET
  options:
    openapi: false

fhir_metadata:
  path: api/fhir/metadata
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::metadata
  defaults:
    permission: none
  methods: GET
  options:
    openapi: false

fhir_create:
  path: api/fhir
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::create
  defaults:
    permission: none
  requirements:
    resource:  DocumentReference
  methods:    POST
  options:
    openapi: false

fhir_update:
  path: api/fhir/{resource}/{resource_id}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::update
  defaults:
    permission: none
  requirements:
    resource:  DocumentReference
  methods:    PUT
  options:
    openapi: false

fhir_delete:
  path: api/fhir/{resource}/{resource_id}
  controller: Ox\Interop\Fhir\Controllers\CFHIRController::delete
  defaults:
    permission: none
  requirements:
    resource:  DocumentReference
  methods:    DELETE
  options:
    openapi: false
