CREATE TABLE IF NOT EXISTS `diplome_autorisation_exercice` (
    `type_identifiant` INT(1) UNSIGNED NOT NULL,
    `identifiant` VARCHAR(11) NOT NULL,
    `identifiant_national` VARCHAR(12) NOT NULL,
    `nom` VARCHAR(50) NOT NULL,
    `prenom` VARCHAR(50) NOT NULL,
    `code_type_diplome` VARCHAR(5) NULL DEFAULT NULL,
    `libelle_type_diplome` VARCHAR(50) NULL DEFAULT NULL,
    `code_diplome` VARCHAR(5) NULL DEFAULT NULL,
    `libelle_diplome` VARCHAR(100) NULL DEFAULT NULL,
    `code_type_autorisation` VARCHAR(10) NULL DEFAULT NULL,
    `libelle_type_autorisation` VARCHAR(100) NULL DEFAULT NULL,
    `code_discipline_autorisation` VARCHAR(10) NULL DEFAULT NULL,
    `libelle_discipline_autorisation` VARCHAR(50) NULL DEFAULT NULL,
    `version` VARCHAR(10) NOT NULL,
    `synchronized` ENUM ('0', '1') DEFAULT '0',
    `diplome_autorisation_exercice_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `code_type_diplome` (`code_type_diplome`),
    INDEX `code_diplome` (`code_diplome`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `savoir_faire` (
    `type_identifiant` INT(1) UNSIGNED NOT NULL,
    `identifiant` VARCHAR(11) NOT NULL,
    `identifiant_national` VARCHAR(12) NOT NULL,
    `nom` VARCHAR(50) NOT NULL,
    `prenom` VARCHAR(50) NOT NULL,
    `code_profession` INT(2) UNSIGNED NOT NULL,
    `libelle_profession` VARCHAR(50) NOT NULL,
    `code_categorie_pro` VARCHAR(1) NOT NULL,
    `libelle_categorie_pro` VARCHAR(50) NOT NULL,
    `code_type_savoir_faire` VARCHAR(10) NOT NULL,
    `libelle_type_savoir_faire` VARCHAR(50) NOT NULL,
    `code_savoir_faire` VARCHAR(10) NOT NULL,
    `libelle_savoir_faire` VARCHAR(100) NOT NULL,
    `version` VARCHAR(10) NOT NULL,
    `synchronized` ENUM ('0', '1') DEFAULT '0',
    `savoir_faire_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `code_profession` (`code_profession`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `personne_exercice` (
    `type_identifiant` INT(1) UNSIGNED NOT NULL,
    `identifiant` VARCHAR(11) NOT NULL,
    `identifiant_national` VARCHAR(12) NOT NULL,
    `code_civilite_exercice` VARCHAR(5) NOT NULL,
    `libelle_civilite_exercice` VARCHAR(50) NOT NULL,
    `code_civilite` VARCHAR(5) NOT NULL,
    `libelle_civilite` VARCHAR(50) NOT NULL,
    `nom` VARCHAR(50) NOT NULL,
    `prenom` VARCHAR(50) NOT NULL,
    `code_profession` INT(2) UNSIGNED NOT NULL,
    `libelle_profession` VARCHAR(50) NOT NULL,
    `code_cat_pro` VARCHAR(5) NOT NULL,
    `libelle_cat_pro` VARCHAR(50) NOT NULL,
    `code_type_savoir_faire` VARCHAR(5) NOT NULL,
    `libelle_type_savoir_faire` VARCHAR(50) NOT NULL,
    `code_savoir_faire` VARCHAR(5) NOT NULL,
    `libelle_savoir_faire` VARCHAR(100) NOT NULL,
    `code_mode_exercice` VARCHAR(1) NOT NULL,
    `libelle_mode_exercice` VARCHAR(8) NOT NULL,
    `siret_site` VARCHAR(14) NOT NULL,
    `siren_site` VARCHAR(9) NOT NULL,
    `finess_site` VARCHAR(9) NOT NULL,
    `finess_etab_juridique` VARCHAR(9) NOT NULL,
    `id_technique_structure` VARCHAR(50) NOT NULL,
    `raison_sociale_site` VARCHAR(255) NOT NULL,
    `enseigne_comm_site` VARCHAR(100) NOT NULL,
    `comp_destinataire` VARCHAR(50) NOT NULL,
    `comp_point_geo` VARCHAR(50) NOT NULL,
    `num_voie` VARCHAR(4) NOT NULL,
    `repetition_voie` VARCHAR(3) NOT NULL,
    `code_type_voie` VARCHAR(5) NOT NULL,
    `libelle_type_voie` VARCHAR(50) NOT NULL,
    `libelle_voie` VARCHAR(50) NOT NULL,
    `mention_distrib` VARCHAR(50) NOT NULL,
    `cedex` VARCHAR(50) NOT NULL,
    `cp` VARCHAR(5) NOT NULL,
    `code_commune` VARCHAR(5) NOT NULL,
    `libelle_commune` VARCHAR(50) NOT NULL,
    `code_pays` VARCHAR(5) NOT NULL,
    `libelle_pays` VARCHAR(10) NOT NULL,
    `tel` VARCHAR(15) NOT NULL,
    `tel2` VARCHAR(15) NOT NULL,
    `fax` VARCHAR(15) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `code_departement` VARCHAR(50) NOT NULL,
    `libelle_departement` VARCHAR(50) NOT NULL,
    `ancien_id_structure` VARCHAR(50) NOT NULL,
    `autorite_enregistrement` VARCHAR(50) NOT NULL,
    `code_secteur_activite` VARCHAR(4) NOT NULL,
    `libelle_secteur_activite` VARCHAR(100) NOT NULL,
    `code_section_tableau_pharma` VARCHAR(2) NOT NULL,
    `libelle_section_tableau_pharma` VARCHAR(255) NOT NULL,
    `version` VARCHAR(10) NOT NULL,
    `synchronized` ENUM ('0', '1') DEFAULT '0',
    `personne_exercice_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `nom` (`nom`),
    INDEX `prenom` (`prenom`),
    INDEX `code_profession` (`code_profession`),
    INDEX `cp` (`cp`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`)
) ENGINE=MyISAM;
